spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testsystem?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
#    docker 이용시
#    url: jdbc:mysql://mysql:3306/testsystem?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: very-secret-key-for-jwt-sign
  access-token-expiration: 600000      # 10분
  refresh-token-expiration: 1209600000 # 14일